name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@1.85.0
    
    - uses: Swatinem/rust-cache@v2
    
    - name: Install critcmp
      run: cargo install critcmp
    
    - name: Run benchmarks on main branch (baseline)
      if: github.event_name == 'pull_request'
      run: |
        git checkout main
        cargo bench --bench bulletproof_bench -- --save-baseline main
    
    - name: Run benchmarks on current branch
      run: |
        git checkout ${{ github.sha }}
        cargo bench --bench bulletproof_bench -- --save-baseline current
    
    - name: Compare benchmarks
      if: github.event_name == 'pull_request'
      run: |
        critcmp main current --threshold 10
        if [ $? -ne 0 ]; then
          echo "Performance regression detected (>10% slowdown)"
          exit 1
        fi
